version: "3"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    image: transcendence-frontend-dev:latest
    container_name: transcendence-front-dev
    volumes:
      - ../frontend/src:/app/src
    networks:
      - transcendence
    depends_on:
      - backend
    expose:
      - 5173
    ports:
      - 5173:5173
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    image: transcendence-backend-dev:latest
    container_name: transcendence-back-dev
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/src:/app/src
    networks:
      - transcendence
    depends_on:
      - db
    expose:
      - 3000
    ports:
      - 3000:3000
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ../backend/.env
    restart: always
    volumes:
      - db_volumes:/var/lib/postgresql/data
    networks:
      - transcendence
    expose:
      - 5432
    ports:
      - 5432:5432
networks:
  transcendence:
    driver: bridge
volumes:
  db_volumes: